container:
  image: ghcr.io/davidbailey00/notion-linux

build_app_task:
  <<: &build_cache
    node_modules_cache:
      folder: node_modules
      fingerprint_script: cat package-lock.json
      populate_script: npm ci
    build_folder_cache:
      folder: build
      fingerprint_script:
        - cat package-lock.json
        - cat scripts/{_variables-*,build,enhance}.sh
  build_app_script:
    - scripts/build.sh
    - scripts/build.sh -b arm64
  enhance_app_script:
    - scripts/enhance.sh
    - scripts/enhance.sh -b arm64

package_deb_task:
  <<: *build_cache
  debs_cache: &debs_cache
    folder: out/debs
    fingerprint_script:
      - cat package-lock.json
      - cat scripts/{_variables-*,build,enhance,package-deb}.sh
      - cat templates/desktop-deb.ejs
  depends_on: build_app
  container:
    cpu: 4
    memory: 10G
  package_deb_script:
    - scripts/package-deb.sh &
    - scripts/package-deb.sh -b arm64 &
    - scripts/package-deb.sh -n notionenhanced &
    - scripts/package-deb.sh -n notionenhanced -b arm64 &
    - wait
    - "[[ $(ls out/debs | wc -l) == 4 ]]"
  deb_artifacts:
    path: "out/debs/*"

package_rpm_task:
  <<: *build_cache
  rpms_cache: &rpms_cache
    folder: out/rpms
    fingerprint_script:
      - cat package-lock.json
      - cat scripts/{_variables-*,build,enhance,package-rpm}.sh
      - cat templates/desktop-rpm.ejs
  depends_on: build_app
  container:
    cpu: 4
  package_rpm_script:
    - scripts/package-rpm.sh &
    - scripts/package-rpm.sh -b arm64 &
    - scripts/package-rpm.sh -n notionenhanced &
    - scripts/package-rpm.sh -n notionenhanced -b arm64 &
    - wait
    - "[[ $(ls out/rpms | wc -l) == 4 ]]"
  rpm_artifacts:
    path: "out/rpms/*"

deploy_to_gemfury_task:
  debs_cache: *debs_cache
  rpms_cache: *rpms_cache
  only_if: $CIRRUS_BRANCH == 'main'
  environment:
    GEMFURY_TOKEN: ENCRYPTED[a7b2cc08cab17b9d9043816cc0e8bdfc3e0b0b59f21c5e920d9f86d0961d61a05959590b90d998134d94828cd6a5a860]
  depends_on:
    - package_deb
    - package_rpm
  deploy_script: scripts/deploy.sh
